## Configmap reference for promethous

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: mongodb
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:30002"]

      - job_name: "kubernetes-pods"
        kubernetes_sd_configs:
          - role: pod
