apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-metrics-app
  namespace: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-metrics-app
  template:
    metadata:
      labels:
        app: go-metrics-app
    spec:
      containers:
        - name: go-metrics-app
          image: ricardbejarano/go-metrics-app:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-metrics-app
  namespace: mongodb
spec:
  selector:
    app: go-metrics-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # Using the existing mapped port
