apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: k8-rs1
spec:
  members: 3
  version: 6.0.5-ent
  type: ReplicaSet

  opsManager:
    configMapRef:
      name: my-project
  credentials: organization-secret

  persistent: false
